/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulobugs;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author joaoflorao
 */
public class Iconsulta_bug extends javax.swing.JFrame {
    private JFileChooser filename;
    
    /**
     * Creates new form Ipessoa
     */
    public Iconsulta_bug() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo_bug = new javax.swing.JLabel();
        lbl_status_bug = new javax.swing.JLabel();
        lbl_descricao_bug = new javax.swing.JLabel();
        lbl_passos_reproducao = new javax.swing.JLabel();
        lbl_classificacao_bug = new javax.swing.JLabel();
        bt_consultar_bug = new javax.swing.JButton();
        btn_limpar_campos_bug = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao_bug = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_passos_reproducao = new javax.swing.JTextArea();
        lbl_anexar_arquivo = new javax.swing.JLabel();
        lbl_id_bug = new javax.swing.JLabel();
        txt_id_bug = new javax.swing.JTextField();
        txt_titulo_bug = new javax.swing.JTextField();
        txt_filename = new javax.swing.JTextField();
        bt_excluir_bug = new javax.swing.JButton();
        bt_editar_bug = new javax.swing.JButton();
        txt_classificacao_bug = new javax.swing.JComboBox<>();
        txt_status_bug = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titulo_bug.setText("Título do Bug:");

        lbl_status_bug.setText("Status:");
        lbl_status_bug.setToolTipText("");

        lbl_descricao_bug.setText("Descrição:");

        lbl_passos_reproducao.setText("Passos de Reprodução:");

        lbl_classificacao_bug.setText("Classificação:");

        bt_consultar_bug.setText("Consultar");
        bt_consultar_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultar_bugActionPerformed(evt);
            }
        });

        btn_limpar_campos_bug.setText("Limpar");
        btn_limpar_campos_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_campos_bugActionPerformed(evt);
            }
        });

        txt_descricao_bug.setColumns(20);
        txt_descricao_bug.setRows(5);
        jScrollPane1.setViewportView(txt_descricao_bug);

        txt_passos_reproducao.setColumns(20);
        txt_passos_reproducao.setRows(5);
        jScrollPane2.setViewportView(txt_passos_reproducao);

        lbl_anexar_arquivo.setText("Anexar arquivo:");

        lbl_id_bug.setText("ID do Bug");

        txt_titulo_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titulo_bugActionPerformed(evt);
            }
        });

        txt_filename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filenameActionPerformed(evt);
            }
        });

        bt_excluir_bug.setText("Excluir");
        bt_excluir_bug.setActionCommand("Excluir");
        bt_excluir_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_bugActionPerformed(evt);
            }
        });

        bt_editar_bug.setText("Editar");
        bt_editar_bug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editar_bugActionPerformed(evt);
            }
        });

        txt_classificacao_bug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não definido", "Desenvolvimento", "Ambiente", "Especificação", "Usabilidade", "Teste", "Melhoria" }));

        txt_status_bug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Em andamento", "Em teste", "Fechado", "Reaberto" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_excluir_bug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_editar_bug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpar_campos_bug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_consultar_bug))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_anexar_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_filename))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_passos_reproducao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_descricao_bug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_status_bug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_titulo_bug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(txt_titulo_bug)
                                    .addComponent(txt_status_bug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_classificacao_bug, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_classificacao_bug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_id_bug, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id_bug)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id_bug)
                    .addComponent(txt_id_bug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo_bug)
                    .addComponent(txt_titulo_bug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_status_bug)
                    .addComponent(txt_status_bug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_descricao_bug)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_passos_reproducao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_anexar_arquivo)
                    .addComponent(txt_filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_classificacao_bug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_classificacao_bug))
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_consultar_bug)
                    .addComponent(btn_limpar_campos_bug)
                    .addComponent(bt_excluir_bug)
                    .addComponent(bt_editar_bug))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        lbl_passos_reproducao.getAccessibleContext().setAccessibleName("Passos de reprodução:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_consultar_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultar_bugActionPerformed

        String id = txt_id_bug.getText();
        
        try {
            
            ConnectDB db = new ConnectDB();
            BugManager manager = new BugManager();
            
            ResultSet rs = manager.ConsultarBug(Integer.parseInt(id));
                
            while (rs.next()) {   
                txt_titulo_bug.setText(rs.getString("titulo"));
                txt_status_bug.setSelectedItem(rs.getString("status"));
                txt_descricao_bug.setText(rs.getString("descricao"));
                txt_passos_reproducao.setText(rs.getString("reproducao"));
                txt_filename.setText(rs.getString("file"));
                txt_classificacao_bug.setSelectedItem(rs.getString("classificacao"));
            }
            
            if (!rs.next() && txt_titulo_bug.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Nenhum bug encontrado para o id: " + id);
                
        } catch (SQLException ex) {
            Logger.getLogger(Iconsulta_bug.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_consultar_bugActionPerformed

    private void btn_limpar_campos_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_campos_bugActionPerformed
        // TODO add your handling code here:
        txt_id_bug.setText("");
        txt_titulo_bug.setText("");
        txt_status_bug.setSelectedItem("Aberto");
        txt_passos_reproducao.setText("");
        txt_descricao_bug.setText("");
        txt_filename.setText("");
        txt_classificacao_bug.setSelectedItem("Não definido");
    }//GEN-LAST:event_btn_limpar_campos_bugActionPerformed

    private void txt_titulo_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titulo_bugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titulo_bugActionPerformed

    private void txt_filenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filenameActionPerformed

    private void bt_excluir_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_bugActionPerformed
        // TODO add your handling code here:
        
        try {
              
            int id = Integer.parseInt(txt_id_bug.getText());
            
            BugManager manager = new BugManager();
        
            this.bt_consultar_bugActionPerformed(evt);
            
            int confirm = JOptionPane.showConfirmDialog(null, "Deseja excluir o bug?");

            if (confirm == 0)
            {   
                manager.ExcluirBug(id);                
                this.btn_limpar_campos_bugActionPerformed(evt);
            }
            
        } 
        catch (Exception e)
        {
            //JOptionPane.showMessageDialog(null, "Informe o ID do bug que deseja excluir!");
            System.out.println(e);
        }
        
    }//GEN-LAST:event_bt_excluir_bugActionPerformed

    private void bt_editar_bugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editar_bugActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bt_editar_bugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iconsulta_bug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iconsulta_bug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iconsulta_bug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iconsulta_bug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iconsulta_bug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consultar_bug;
    private javax.swing.JButton bt_editar_bug;
    private javax.swing.JButton bt_excluir_bug;
    private javax.swing.JButton btn_limpar_campos_bug;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_anexar_arquivo;
    private javax.swing.JLabel lbl_classificacao_bug;
    private javax.swing.JLabel lbl_descricao_bug;
    private javax.swing.JLabel lbl_id_bug;
    private javax.swing.JLabel lbl_passos_reproducao;
    private javax.swing.JLabel lbl_status_bug;
    private javax.swing.JLabel lbl_titulo_bug;
    private javax.swing.JComboBox<String> txt_classificacao_bug;
    private javax.swing.JTextArea txt_descricao_bug;
    private javax.swing.JTextField txt_filename;
    private javax.swing.JTextField txt_id_bug;
    private javax.swing.JTextArea txt_passos_reproducao;
    private javax.swing.JComboBox<String> txt_status_bug;
    private javax.swing.JTextField txt_titulo_bug;
    // End of variables declaration//GEN-END:variables
}
